
#define SUPPORT_TOWER_COIN	120
#define ARCHER_TOWER_COIN	150
#define	MAGIC_TOWER_COIN	100
#define STONE_TOWER_COIN	120

#define SUPPORT_TOWER	1
#define MAGIC_TOWER		2
#define ARCHER_TOWER	3
#define STONE_TOWER		4

#define ENEMY_HEATH		100
#define ARMY_HEATH		100